import { useState, useEffect } from 'react';
import { Plane } from 'lucide-react';
import { Tabs, type TabType } from './components/Tabs';
import { SocialTab } from './components/SocialTab';
import { CopywritingTab } from './components/CopywritingTab';
import { BannerTab } from './components/BannerTab';
import { ImageEditTab } from './components/ImageEditTab';
import { ResultPanel } from './components/ResultPanel';
import { useStore } from './store/useStore';
import { LandingPage } from './pages/LandingPage';

const Workspace = ({ onBack, initialTab }: { onBack: () => void, initialTab?: TabType }) => {
  const [activeTab, setActiveTab] = useState<TabType>(initialTab || 'social');
  const [campaignType, setCampaignType] = useState('sale');
  const [description, setDescription] = useState('');

  const { createSocialJob, createCopyJob, createBannerJob, pollJobStatus, jobs } = useStore();

  useEffect(() => {
    if (initialTab) {
      setActiveTab(initialTab);
    }
  }, [initialTab]);

  const handleSocialSubmit = async (data: { campaign_type: string; description: string }) => {
    const jobId = await createSocialJob(data.campaign_type, data.description);
    pollJobStatus(jobId);
  };

  const handleCopySubmit = async (data: { channel: string; brief: string; tone: string }) => {
    const jobId = await createCopyJob(data.channel, data.brief, data.tone);
    pollJobStatus(jobId);
  };

  const handleBannerSubmit = async (data: { brief: string; aspect_ratio: string }) => {
    const jobId = await createBannerJob(data.brief, data.aspect_ratio);
    pollJobStatus(jobId);
  };

  const handleImageEditSubmit = async (data: any) => {
    const jobId = await createBannerJob(data.brief, '16:9');
    pollJobStatus(jobId);
  };

  return (
    <div className="min-h-screen bg-gray-50 animate-fade-in">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-gray-200 sticky top-0 z-10">
        <div className="px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Plane size={32} color="#1A1AAF" />
            <h1 className="text-2xl font-bold text-indigo-blue">6E Creative Studio</h1>
          </div>
          <button
            onClick={onBack}
            className="text-sm font-bold text-gray-400 hover:text-indigo-blue transition-colors flex items-center gap-2"
          >
            ← BACK TO PROJECTS
          </button>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex" style={{ height: 'calc(100vh - 73px)' }}>
        {/* Left Sidebar - Campaign Details */}
        <aside className="w-96 bg-white border-r border-gray-200 overflow-y-auto">
          <div className="p-8">
            <h2 className="text-xl font-bold mb-6 text-indigo-dark">Campaign Details</h2>

            <div className="space-y-6">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-3">
                  CAMPAIGN TYPE *
                </label>
                <select
                  value={campaignType}
                  onChange={e => setCampaignType(e.target.value)}
                  className="input"
                >
                  <option value="sale">Flash Sale</option>
                  <option value="new_route">New Route Launch</option>
                  <option value="brand">Brand Awareness</option>
                  <option value="seasonal">Seasonal Campaign</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-bold text-gray-700 mb-3">
                  DESCRIPTION *
                </label>
                <textarea
                  value={description}
                  onChange={e => setDescription(e.target.value)}
                  className="input"
                  rows={8}
                  placeholder="e.g. Launching a new direct flight from Delhi to London. Focus on comfort and on-time performance."
                />
              </div>

              <button
                className="btn-primary w-full shadow-lg shadow-indigo-200"
                disabled={!description.trim()}
              >
                Sync All Modules
              </button>
              
              <p className="text-[10px] text-gray-400 text-center leading-relaxed">
                Content generated by AI should be reviewed by the Marketing team before publishing.
              </p>
            </div>
          </div>
        </aside>

        {/* Main Content Area */}
        <main className="flex-1 overflow-hidden flex flex-col bg-gray-50">
          {/* Tabs */}
          <div className="bg-white border-b border-gray-200 px-8 pt-4">
            <Tabs activeTab={activeTab} onTabChange={setActiveTab} />
          </div>

          {/* Tab Content */}
          <div className="flex-1 overflow-y-auto p-8">
            {activeTab === 'imageEdit' ? (
              <ImageEditTab onSubmit={handleImageEditSubmit} />
            ) : (
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-[1600px] mx-auto w-full">
                <div className="card shadow-sm h-fit">
                  {activeTab === 'social' && <SocialTab onSubmit={handleSocialSubmit} />}
                  {activeTab === 'copywriting' && <CopywritingTab onSubmit={handleCopySubmit} />}
                  {activeTab === 'banner' && <BannerTab onSubmit={handleBannerSubmit} />}
                </div>

                <div className="h-[calc(100vh-180px)]">
                  <ResultPanel jobs={jobs} />
                </div>
              </div>
            )}
          </div>
        </main>
      </div>
    </div>
  );
};

const App = () => {
  const [navigation, setNavigation] = useState<{ projectId: string | null, tab: TabType | null }>({
    projectId: null,
    tab: null
  });

  if (!navigation.projectId) {
    return (
      <LandingPage 
        onProjectSelect={(id, tab) => setNavigation({ projectId: id, tab: (tab as TabType) || 'social' })} 
      />
    );
  }

  return (
    <Workspace 
      initialTab={navigation.tab || 'social'} 
      onBack={() => setNavigation({ projectId: null, tab: null })} 
    />
  );
};

export default App;
